// models.js
// Developer Reuse Metadata Profile (12 fields) implementation
// Fields:
// id, modelName, organisation, modelStatus, aiTask, inputSpecification, outputSpecification,
// architecture, trainingDataOrigin, primaryPerformanceMetric, license, accessLink, moreInformation
//
// Note: Keep text factual, technically precise, and explicit when information is missing.

window.MODELS = [
  {
    id: "model-001",
    modelName: "Land Cover Classification (Sentinel-2)",
    organisation: "Esri",
    modelStatus: "Production ready",
    aiTask: "Semantic segmentation",
    inputSpecification: "Sentinel-2 imagery, 10m, EPSG:3857.",
    outputSpecification: "Raster with CLC 2018 classes.",
    architecture: "U-Net",
    trainingDataOrigin: "CORINE Land Cover 2018.",
    primaryPerformanceMetric: "Overall accuracy 84%.",
    license: "Esri Master License Agreement",
    accessLink: "https://www.arcgis.com/home/item.html?id=afd124844ba84da69c2c533d4af10a58",
    moreInformation: "Source: Esri Living Atlas (model entry)."
  },
  {
    id: "model-002",
    modelName: "Buildings detection model",
    organisation: "Lantmäteriet",
    modelStatus: "In production",
    aiTask: "Object detection",
    inputSpecification: "The model requires true orthos and a normalised elevation model in tiff format. Input images must be of size 512x512 pixels. Orthos must be provided as a 4-channel image with 25 cm resolution.",
    outputSpecification: "The model outputs a classified raster with the same spatial resolution as the input imagery. Each pixel is assigned a value 1 or 0 (building – not building). The output preserves the input coordinate reference system.",
    architecture: "Segformer",
    trainingDataOrigin: "True orthophotos (0.25 cm) and normalised elevation model.",
    primaryPerformanceMetric: "F-score: 95%.",
    license: "Model not available for external use",
    accessLink: "N/A",
    moreInformation: "N/A"
  },
  {
    id: "model-003",
    modelName: "Road detection model",
    organisation: "Lantmäteriet",
    modelStatus: "Experimental",
    aiTask: "Object detection",
    inputSpecification: "The model requires true orthos and a normalised elevation model in tiff format. Input images must be of size 512x512 pixels. Orthos must be provided as a 4-channel image with 25 cm resolution.",
    outputSpecification: "The model outputs a classified raster with the same spatial resolution as the input imagery. Each pixel is assigned a value 1 or 0 (road – not road). The output preserves the input coordinate reference system.",
    architecture: "Segformer",
    trainingDataOrigin: "The model has been trained on true orthos from different parts of Sweden. The normalised elevation model is based on Lidar data (1 pts/sqm)",
    primaryPerformanceMetric: "F-score: 85%.",
    license: "Model not available for external use",
    accessLink: "N/A",
    moreInformation: "N/A"
  }  ,
  {
    id: "model-005",
    modelName: "YOLOv8 Road Asset Detection for 3D Mapping",
    organisation: "Cyclomedia",
    modelStatus: "Validated",
    aiTask: "Object detection",
    inputSpecification: "Used within Cyclomedia 3D mapping workflows. Exact sensor types, formats, spatial resolution, and preprocessing steps are not specified.",
    outputSpecification: "Detected road assets and defects for infrastructure assessment. Output schema, geometry type, and confidence scores are not specified.",
    architecture: "YOLOv8",
    trainingDataOrigin: "Not explicitly stated. Likely based on proprietary outdoor environment data captured by Cyclomedia, but this is not formally specified in the source.",
    primaryPerformanceMetric: "Not stated in the source.",
    license: "Not stated in the source.",
    accessLink: "Not stated in the source.",
    moreInformation: "Part of Cyclomedia Insights 360 platform for infrastructure and municipal applications."
  },
  {
    id: "model-006",
    modelName: "Segment Anything for 3D Outdoor Mapping",
    organisation: "Cyclomedia",
    modelStatus: "Validated",
    aiTask: "Semantic segmentation",
    inputSpecification: "Used within 3D mapping workflows. Exact input modalities, formats, CRS, and preprocessing requirements are not specified.",
    outputSpecification: "Segmented objects for 3D environment representation. Output structure and class definitions are not specified.",
    architecture: "Segment Anything",
    trainingDataOrigin: "Not stated in the source.",
    primaryPerformanceMetric: "Not stated in the source.",
    license: "Not stated in the source.",
    accessLink: "Not stated in the source.",
    moreInformation: "Used in combination with object detection models to enhance 3D mapping accuracy."
  },
  {
    id: "model-007",
    modelName: "U-Net Forest and Land Segmentation",
    organisation: "Institut Cartogràfic i Geològic de Catalunya (ICGC)",
    modelStatus: "Experimental",
    aiTask: "Semantic segmentation",
    inputSpecification: "LiDAR data and hyperspectral data are referenced. Exact formats, resolution, CRS, and preprocessing steps are not specified.",
    outputSpecification: "Segmented vegetation and land features. Output schema, class ontology, and confidence handling are not specified.",
    architecture: "U-Net",
    trainingDataOrigin: "Based on ICGC geospatial datasets. Specific dataset names, labeling protocols, and availability are not provided.",
    primaryPerformanceMetric: "Not stated in the source.",
    license: "Not stated in the source.",
    accessLink: "Not stated in the source.",
    moreInformation: "Used in projects such as vegetation monitoring and forest segmentation."
  },
  {
    id: "model-008",
    modelName: "Mask R-CNN for Topographic Feature Detection",
    organisation: "Estonian Land Board",
    modelStatus: "Validated",
    aiTask: "Object detection",
    inputSpecification: "Orthophotos, ALS derivatives, and vector data are used. Exact formats, schemas, CRS, and preprocessing requirements are not specified.",
    outputSpecification: "Detected features such as buildings, solar parks, roads, and water bodies. Output schema and confidence representation are not specified.",
    architecture: "Mask R-CNN",
    trainingDataOrigin: "Derived from Estonian topographic datasets. Dataset names, temporal scope, and availability are not specified.",
    primaryPerformanceMetric: "Precision improvements are reported, but no quantitative metrics are provided.",
    license: "Not stated in the source.",
    accessLink: "Not stated in the source.",
    moreInformation: "Used for updating the Estonian Topographic Database (ETAK)."
  },
  {
    id: "model-009",
    modelName: "SpaCy Named Entity Recognition for Deed Processing",
    organisation: "Kadaster",
    modelStatus: "Validated",
    aiTask: "Named entity recognition",
    inputSpecification: "Text from deed documents processed via OCR and preprocessing pipelines. Exact formats, languages, and schema requirements are not specified.",
    outputSpecification: "Extracted structured entities from legal text. Entity schema, output format, and confidence scores are not specified.",
    architecture: "SpaCy with custom labels and additional training data",
    trainingDataOrigin: "Custom labeled training data for cadastral documents. Dataset details and availability are not specified.",
    primaryPerformanceMetric: "Not stated in the source.",
    license: "Not stated in the source.",
    accessLink: "Not stated in the source.",
    moreInformation: "Supports deed registration workflows; a future goal mentioned in the source is automated parcel signaling."
  },
  {
    id: "model-010",
    modelName: "YOLO-based Transport Network Detection",
    organisation: "IGN Spain",
    modelStatus: "Validated",
    aiTask: "Object detection",
    inputSpecification: "High-resolution PNOA imagery at 0.15 m resolution is referenced. Exact format, CRS, tiling, and preprocessing steps are not specified.",
    outputSpecification: "Detected transport features such as road markings, arrows, roundabouts, and bridges. Output schema and confidence scores are not specified.",
    architecture: "YOLOv5 / YOLOv8",
    trainingDataOrigin: "PNOA imagery for Spain. Dataset structure, labeling process, and availability are not specified.",
    primaryPerformanceMetric: "Not stated in the source.",
    license: "Not stated in the source.",
    accessLink: "Not stated in the source.",
    moreInformation: "Used for transport network maintenance and cartographic updates."
  },
  {
    id: "model-011",
    modelName: "Lantmäteriet bergidagen",
    organisation: "Lantmäteriet",
    modelStatus: "Experimental",
    aiTask: "Berg",
    inputSpecification: "ORto",
    outputSpecification: "Raster",
    architecture: "Segformer",
    trainingDataOrigin: "Sweden",
    primaryPerformanceMetric: "85%",
    license: "",
    accessLink: "",
    moreInformation: ""
  }
];
